### DISCUSSION TITLE
[CONCEPT] How to make a 3D flipping card effect

### DISCUSSION THREAD

**Discussion by LePhenix47** [LePhenix47/Dev-Portfolio_Younes-Lahouiti#23] [Concept]
## Step 1: Set up the HTML structure
Create a container div that will hold the front and back card divs. Give it an appropriate class or ID for styling purposes. Inside the container, create a front card div and a back card div. You can add content to these divs as needed.

```html
<div class="container">
  <div class="card front">
    <!-- Front card content goes here -->
  </div>
  <div class="card back">
    <!-- Back card content goes here -->
  </div>
</div>
```

## Step 2: Style the container
In your CSS, target the container and apply the following properties to enable the 3D effect:

```css
.container {
  transform-style: preserve-3d;
  perspective: [value in px];
  perspective-origin: [top, bottom, left, or right];
}
```

The transform-style: preserve-3d; property enables the 3D space for the child elements, and perspective controls the depth of the 3D effect. Adjust the value to your liking. The perspective-origin property determines the 3D vanishing point, which defines the origin of the perspective property.

## Step 3: Style the front and back cards
Target both the front and back card divs and apply the following styles:

```css
.card {
  backface-visibility: hidden;
  transition: transform 550ms ease-in-out;
}
```

The backface-visibility: hidden; property ensures that the back face of the card is not visible when flipped. The transition property adds a smooth transition effect when the transform property changes.

Step 4: Set the initial state of the cards
By default, the front card should be visible, and the back card should be hidden. You can use classes or state management to toggle the visibility. Let's assume the back card is initially hidden.

```css
.card.back {
  transform: rotateY(-180deg);
}
```

Here, we use the transform property to rotate the back card along the Y-axis by 180 degrees, effectively hiding it.

That's it! With these steps, you've created the foundation for a 3D card flip effect.
