### ISSUE TITLE
[BUG] The `<footer>` isn't sticking down

### ISSUE THREAD

**Issue by LePhenix47** [LePhenix47/Dev-Portfolio_Younes-Lahouiti#34]
Add these properties to fix it to the `<div id="__next">`:

```css
#__next {
    display: grid;
    grid-template-rows: auto 1fr auto; // auto for header, 1fraction for the main and auto for footer
    min-height: 100svh;
}
```
